---
title: "Final Graph Models"
author: "Lucia Guintu"
date: "5/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#install.packages("shinySIR")
#install.packages("devtools")
#library("devtools")

#install_github("SineadMorris/shinySIR")
```

```{r}
#library(shinySIR)
#run_shiny(model = "SIR")
```
```{r}
library(tidyverse)
library(deSolve)
library(lubridate)
library(ggforce)
library(ggrepel)
library(grid)
library(gridExtra)
# library(sysfonts)
# library(showtext)
# font_add("minion", regular = "Minion Pro Regular.ttf",
#          bold = "Minion Pro Bold.ttf", italic = "Minion Pro Cond Italic.otf")
#showtext_auto() ## automatically use showtext for new devices
#install.packages("extrafont")

#library(extrafont)
#font_import()
#loadfonts()
myFont<-"sans"
```

```{r}
data<-read.csv("covidtesting.csv")
data<-data %>% 
  mutate(active=Confirmed.Positive-Number.of.patients.hospitalized.with.COVID.19)
Infected<-subset(data,Reported.Date>=ymd("2020-12-25") & Reported.Date<=ymd("2021-04-02"))$Confirmed.Positive
Hospital<-subset(data,Reported.Date>=ymd("2020-12-25") & Reported.Date<=ymd("2021-04-02"))$Number.of.patients.hospitalized.with.COVID.19
Fatal<-subset(data,Reported.Date>=ymd("2020-12-25") & Reported.Date<=ymd("2021-04-02"))$Deaths

```
```{r}
vax_data<-read.csv("vaccine_doses (2).csv")
Vaccinated<-subset(vax_data,report_date>=ymd("2020-12-26") & report_date<=ymd("2021-04-03"))$total_individuals_fully_vaccinated
```






```{r}
# N = Total population
#S = Susceptible, E = Exposed, I = Infectious, H = Hospitalized, R = Recovered, Fa = Fatal, V = Vaccinated

#v = vaccination rate, ev = vaccine efficacy rate, im  - 1/(time it takes to lose immunity), beta - transmission rate, l  - 1/(latency for the onset of symptoms),
#rh  - Recovery rate of hospitalized individuals, ro - Rate of recovery for infected people who just recovered on their own, 
#h  - Rate of hospitalization (probability of hospitalization * 1/num days hospitalized)
#dl  - Rate of death occurred in LTC (death per day in LTC/total infectious population + death per day in LT),
#dh  - Rate of death occurred in hospitals (assumptions made) average(death per day in hospitals/total hospitalized population+death per day in hospitals)

SEIR1 <- function(time, current_state, params){

  with(as.list(c(current_state, params)),{
    v = ifelse(
        (time <= 12),
        0, 0.000130
        )
    N <- S+E+I+H+R+Fa+V
    dS <- -(beta*S*I)/N + im*R - (v*ev*S)
    dE <- (beta*S*I)/N - l*E
    dI <- l*E - ro*I - dl*I
    dH <- ro*h*I - rh*H - dh*H
    dR <- (1-h)*ro*I + rh*H - im*R
    dFa <- dl*I + dh*H
    dV <- (v*ev*S)

    return(list(c(dS, dE, dI, dH, dR, dFa,dV)))
  })
}


params <- c(ev=0.942, im=1/140, beta=1.07/4.5, l=1/5.5, rh=1/15, ro=1/14, h=0.074, dl=0.00291, dh=0.015)

initial_state <- c(S=13791520, E=3152 , I=18690,  H=998,R=105512,Fa=4321,V=0)

times <- 0:98


model <- ode(initial_state, times, SEIR1, params)
summary(model)
out.df<-as.data.frame(model)

# add a Date column and the observed incidence,fatal,hospital, and vaccinated data
out.df <- out.df %>%
  mutate(
    Date = ymd("2020-12-26") + days(times),
    IEH=I+E+H,
  )


 # out.df <- out.df %>%
 #  mutate(
 #    percent_vaccinated=V/13924193
 #  )

infect<-data %>% 
  filter(Reported.Date>= ymd("2020-12-01")) %>% 
  filter(Reported.Date <= ymd("2021-04-03"))

vax<-vax_data %>% 
  filter(report_date>= ymd("2020-12-01")) %>% 
  filter(report_date <= ymd("2021-04-03"))
```


```{r}


p<-ggplot() +
  geom_line(data=out.df,aes(x=Date,y=I,color="Model")) +
  geom_point(aes(x=ymd(Reported.Date),y=active,color="Actual data"), data=infect,size=0.5) +
  geom_vline(aes(xintercept = ymd("2020-12-26"),color="Lockdown starts (2020-12-26)"),show.legend = F,linetype="twodash") +
  geom_vline(aes(xintercept = ymd("2021-01-25"),color="Lockdown ends (2021-01-25)"),show.legend = F,linetype="twodash") +
  scale_y_continuous(labels = scales::comma,trans="log10") +
  scale_colour_manual("",breaks=c("Actual data","Model","Lockdown starts (2020-12-26)","Lockdown ends (2021-01-25)"),
values=c("#E31837","#E31837","#F17E68","#797a7c"),
guide = guide_legend(nrow=2,override.aes = list(
                         linetype = c(0,1,6,6), shape=c(20,NA,NA,NA)))) +
  
  annotate("segment", x = ymd("2021-01-25"), xend=ymd("2021-01-25"), y = 23620, yend = 166748,
           arrow = arrow(length = unit(.2,"cm")),size = 0.9) +

  annotate("text", label="6.1x more cases", x = ymd("2021-01-25"), y = 75000,hjust=-0.1,size=3,fontface="bold") +
  
  labs(title="",y="Prevalent cases (log scale)") +
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5),axis.title=element_text(size=13),text=element_text(family=myFont,size=16),legend.position="bottom")


p2<-ggplot() +
  geom_line(data=out.df,aes(x=Date,y= H,color="Model")) +
  geom_point(aes(x=ymd(Reported.Date),y=Number.of.patients.hospitalized.with.COVID.19,color="Actual data"), data=infect,size=0.5) +
  geom_vline(aes(xintercept = ymd("2020-12-26")),color="#F17E68",linetype="twodash") +
  geom_vline(aes(xintercept = ymd("2021-01-25")),color = "#797a7c",linetype="twodash") +
  scale_y_continuous(labels = scales::comma,trans="log10") +
  scale_colour_manual("",breaks=c("Actual data","Model"),
values=c("#8E4465","#8E4465"),
guide = guide_legend(override.aes = list(
                         linetype = c(0,1), shape=c(20,NA)))) +
  
  annotate("segment", x = ymd("2021-01-25"), xend=ymd("2021-01-25"), y = 1398, yend = 5377,
           arrow = arrow(length = unit(.2,"cm")),size = 0.9) +

  annotate("text", label="2.8x more", x = ymd("2021-01-25"), y = 2200,hjust=-0.2,size=3,fontface="bold") +
  annotate("text", label="hospitalized", x = ymd("2021-01-25"), y = 2200,hjust=-0.2,vjust=1.8,size=3,fontface="bold") +

  
  labs(title="",y="# of people hospitalized (log scale)") +
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5),axis.title=element_text(size=13),text=element_text(family=myFont,size=16),legend.position="bottom")


p3<-ggplot() +
  geom_line(data=out.df,aes(x=Date,y=Fa,color="Model")) +
  geom_point(aes(x=ymd(Reported.Date),y=Deaths,color="Actual data"), data=infect,size=0.5) +
  geom_vline(aes(xintercept = ymd("2020-12-26")),color="#F17E68",linetype="twodash") +
  geom_vline(aes(xintercept = ymd("2021-01-25")),color = "#797a7c",linetype="twodash") +
  scale_y_continuous(labels = scales::comma,trans="log10") +
  scale_colour_manual(" ",breaks=c("Actual data","Model"),
values=c("#004658","#004658"),
guide = guide_legend(override.aes = list(
                         linetype = c(0,1), shape=c(20,NA)))) +
  
  annotate("segment", x = ymd("2021-01-25"), xend=ymd("2021-01-25"), y = 5846, yend = 10644,
           arrow = arrow(length = unit(.2,"cm")),size = 0.9) +

  annotate("text", label="0.82x more deaths", x = ymd("2021-01-25"), y = 8500,hjust=-0.1,size=3,fontface="bold") +
  
  labs(title="",y="Total deaths (log scale)") +
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5),axis.title=element_text(size=13),text=element_text(family=myFont,size=16),legend.position="bottom")

ggsave("plot1(2).png",plot=grid.arrange(p, p2, p3, ncol=3, top = textGrob("No winter 2020 lockdown",just = c("centre","top"),gp=gpar(fontsize=24,fontfamily=myFont,fontface="bold"))),width=10.665,height=4.1,dpi=300,limitsize = F)
```

```{r}

full1<-ggplot(data=out.df, aes(x=Date)) +
   geom_line(aes(y = S, color = "Susceptible")) +
   geom_line(aes(y = E, colour = "Exposed")) +
   geom_line(aes(y = I, colour = "Infectious")) +
   geom_line(aes(y = H, colour = "Hospitalized")) +
   geom_line(aes(y = R, colour = "Recovered")) + 
   geom_line(aes(y = Fa, colour = "Fatal")) +
   geom_line(aes(y = V, colour = "Vaccinated")) +
  theme_minimal() +
  scale_y_continuous(labels = scales::comma) +
  scale_colour_manual("Compartments",
breaks=c("Susceptible","Exposed","Infectious","Hospitalized","Recovered","Fatal","Vaccinated"),
values=c("#FFc31f","#F17E68","#E31837","#8E4465","#008BB0","#004658","#797A7C")) +
  labs(y="Number of people", x="Date", title = "SEIHRFV Model (No winter 2020 lockdown)") +
  theme(plot.title = element_text(hjust = 0.5,face="bold"),text=element_text(family=myFont,size=13))

ggsave("full_model_1(2).png",plot=full1,width=6.22,height=4.1,dpi=300,limitsize = F)
```




```{r}

# Infected2<-subset(data,Reported.Date>=ymd("2021-04-02") & Reported.Date<=ymd("2021-05-20"))$Confirmed.Positive
# Hospital2<-subset(data,Reported.Date>=ymd("2021-04-02") & Reported.Date<=ymd("2021-05-20"))$Number.of.patients.hospitalized.with.COVID.19
# Fatal2<-subset(data,Reported.Date>=ymd("2021-04-02") & Reported.Date<=ymd("2021-05-20"))$Deaths
# 
# Vaccinated2<-subset(vax_data,report_date>=ymd("2021-04-02") & report_date<=ymd("2021-05-20"))$total_individuals_fully_vaccinated
```

```{r optimizebeta}
#OPTIMIZE BETA
# optimdata<-read.csv("covidExposed1.csv")
# optimdata<-optimdata %>% 
#   mutate(active=Confirmed.Positive-Number.of.patients.hospitalized.with.COVID.19)
# 
# SEIRo <- function(time, current_state, params){
# 
#   with(as.list(c(current_state, params)),{
#     N <- S+E+I+H+R+Fa+V
#     dS <- -(beta*S*I)/N + im*R - (v*ev*S)
#     dE <- (beta*S*I)/N - l*E
#     dI <- l*E - ro*I - dl*I
#     dH <- ro*h*I - rh*H - dh*H
#     dR <- (1-h)*ro*I + rh*H - im*R
#     dFa <- dl*I + dh*H
#     dV <- (v*ev*S)
# 
#     return(list(c(dS, dE, dI, dH, dR, dFa,dV)))
#   })
# }
# 
# 
# #params <- c(v= 0.000244, ev=0.942, im=1/140, beta=1.14/4.5,  l=1/5.5, rh=1/15, ro=1/14, h=0.074, dh=0.0156, dl=0.000236 )
# 
# initial_state <- c(S=13345264, E=4728, I=20854,  H=1162,R=224423,Fa=7412,V=320350)
# 
# times <- 0:13
# 
# Exposed<-optimdata$Exposed
# 
# RSS <- function(parameters) {
#   
#   params <- c(beta=parameters,v= 0.000244, ev=0.942, im=1/140, rh=1/15, ro=1/14, h=0.074, dh=0.0156, dl=0.000236 )
#   return(parameters)
#    out <- ode(y = initial_state, times = times, func = SEIRo, parms = params)
#    fit <- out[, 3]
#    sum((Exposed - fit)^2)
#    return(fit)
# }
# 
# Opt <- optim(c(0.5),
#   RSS,
#   method = "L-BFGS-B",
#   lower = c(0, 0),
#   upper = c(1, 1)
# )
```

```{r}
#Second lockdown


SEIR <- function(time, current_state, params){

  with(as.list(c(current_state, params)),{
    N <- S+E+I+H+R+Fa+V
    dS <- -(beta*S*I)/N + im*R - (v*ev*S)
    dE <- (beta*S*I)/N - l*E
    dI <- l*E - ro*I - dl*I
    dH <- ro*h*I - rh*H - dh*H
    dR <- (1-h)*ro*I + rh*H - im*R
    dFa <- dl*I + dh*H
    dV <- (v*ev*S)

    return(list(c(dS, dE, dI, dH, dR, dFa,dV)))
  })
}
initial_state <- c(S=13345264, E=4728, I=20854,  H=1162,R=224423,Fa=7412,V=320350)
params <- c(v= 0.000244, ev=0.942, im=1/140, beta=1.14/4.5,  l=1/5.5, rh=1/15, ro=1/14, h=0.074, dh=0.0156, dl=0.000236 )
times <- 0:153
model2 <- ode(initial_state, times, SEIR, params)
summary(model2)
out2<-as.data.frame(model2)

# add a Date column and the observed incidence data

library(lubridate)

out2 <- out2 %>%
  mutate(
    Date = ymd("2021-04-03") + days(times),
    IEH=I+E+H
    # actual_infected=Infected2,
    # actual_fatal=Fatal2,
    # actual_hospital=Hospital2,
    # actual_vaccinated=Vaccinated2
  )

infect<-data %>% 
  filter(Reported.Date>= ymd("2021-03-20")) %>% 
  filter(Reported.Date <= ymd("2021-05-29"))
vax<-vax_data %>% 
  filter(report_date>= ymd("2021-03-20")) %>% 
  filter(report_date <= ymd("2021-05-29"))
```



```{r}
full2<-ggplot(data=out2, aes(x=Date)) +
   geom_line(aes(y = S, color = "Susceptible")) +
   geom_line(aes(y = E, colour = "Exposed")) +
   geom_line(aes(y = I, colour = "Infectious")) +
   geom_line(aes(y = H, colour = "Hospitalized")) +
   geom_line(aes(y = R, colour = "Recovered")) + 
   geom_line(aes(y = Fa, colour = "Fatal")) +
   geom_line(aes(y = V, colour = "Vaccinated")) +
  theme_minimal() +
  scale_y_continuous(labels = scales::comma) +
  scale_colour_manual("Compartments",
breaks=c("Susceptible","Exposed","Infectious","Hospitalized","Recovered","Fatal","Vaccinated"),
values=c("#FFc31f","#F17E68","#E31837","#8E4465","#008BB0","#004658","#797A7C")) +
  labs(y="Number of people", x="Date", title = "SEIHRFV Model (No spring 2021 lockdown)") +
  theme(plot.title = element_text(hjust = 0.5,face="bold"),text=element_text(family=myFont,size=13))
ggsave("full_model_2(2).png",plot=full2,width=6.22,height=4.1,dpi=300,limitsize = F)
```



```{r}



g<-ggplot() +
  geom_line(data=out2,aes(x=Date,y=I,color="Model")) +
  geom_point(aes(x=ymd(Reported.Date),y=active,color="Actual data"), data=infect,size=0.5) +
    geom_vline(aes(xintercept = ymd("2021-04-03"),color="Lockdown starts (2021-04-03)"),show.legend = F,linetype="twodash") +
  geom_vline(aes(xintercept = ymd("2021-05-29"),color="Lockdown ends (2021-05-29)"),show.legend = F,linetype="twodash") +
  scale_y_continuous(labels = scales::comma,trans="log10") +
scale_colour_manual("",breaks=c("Actual data","Model","Lockdown starts (2021-04-03)","Lockdown ends (2021-05-29)"),
values=c("#E31837","#E31837","#F17E68","#797a7c"),
guide = guide_legend(nrow=2,override.aes = list(
                         linetype = c(0,1,6,6), shape=c(20,NA,NA,NA)))) +
  labs(title="",y="Prevalent cases (log scale)") +
  
  annotate("segment", x = ymd("2021-05-29"), xend=ymd("2021-05-29"), y = 14423, yend = 1632544,
           arrow = arrow(length = unit(.2,"cm")),size = 0.9) +

  annotate("text", label="112.2x more cases", x = ymd("2021-05-29"), y = 200000,hjust=-0.1,size=3,fontface="bold") +
  
  theme_minimal()+
theme(plot.title = element_text(hjust = 0.5),axis.title=element_text(size=13),text=element_text(family=myFont,size=16),legend.position="bottom")

g2<-ggplot() +
  geom_line(data=out2,aes(x=Date,y= H,color="Model")) +
  geom_point(aes(x=ymd(Reported.Date),y=Number.of.patients.hospitalized.with.COVID.19,color="Actual data"), data=infect,size=0.5) +
  geom_vline(aes(xintercept = ymd("2021-04-03")),color="#F17E68",linetype="twodash") +
  geom_vline(aes(xintercept = ymd("2021-05-29")),color = "#797a7c",linetype="twodash") +
  scale_y_continuous(labels = scales::comma,trans="log10") +
  scale_colour_manual("",breaks=c("Actual data","Model"),
values=c("#8E4465","#8E4465"),
guide = guide_legend(override.aes = list(
                         linetype = c(0,1), shape=c(20,NA)))) +
  labs(title="",y="# of people hospitalized (log scale)") +
  
    annotate("segment", x = ymd("2021-05-29"), xend=ymd("2021-05-29"), y = 934, yend = 56757,
           arrow = arrow(length = unit(.2,"cm")),size = .9) +

  annotate("text", label="59.8x more", x = ymd("2021-05-29"), y = 10000,hjust=-0.2,size=3,fontface="bold") +
  annotate("text", label="hospitalized", x = ymd("2021-05-29"), y = 10000,hjust=-0.2,vjust=1.8,size=3,fontface="bold") +
  
  theme_minimal()+
theme(plot.title = element_text(hjust = 0.5),axis.title=element_text(size=13),text=element_text(family=myFont,size=16),legend.position="bottom")


g3<-ggplot() +
  geom_line(data=out2,aes(x=Date,y=Fa,color="Model")) +
  geom_point(aes(x=ymd(Reported.Date),y=Deaths,color="Actual data"), data=infect,size=0.5) +
  geom_vline(aes(xintercept = ymd("2021-04-03")),color="#F17E68",linetype="twodash") +
  geom_vline(aes(xintercept = ymd("2021-05-29")),color = "#797a7c",linetype="twodash") +
  scale_y_continuous(labels = scales::comma,trans="log10") +
  scale_colour_manual(" ",breaks=c("Actual data","Model"),
values=c("#004658","#004658"),
guide = guide_legend(override.aes = list(
                         linetype = c(0,1), shape=c(20,NA)))) +
  labs(title="",y="Total deaths (log scale)") +
  
  annotate("segment", x = ymd("2021-05-29"), xend=ymd("2021-05-29"), y = 8726, yend = 23701,
           arrow = arrow(length = unit(.2,"cm")),size = .9) +

  annotate("text", label="1.7x more deaths", x = ymd("2021-05-29"), y = 13000,hjust=-0.1,size=3,fontface="bold") +
  
  theme_minimal()+
theme(plot.title = element_text(hjust = 0.5),axis.title=element_text(size=13),text=element_text(family=myFont,size=16),legend.position="bottom")

ggsave("plot2(2).png",plot=grid.arrange(g, g2, g3, ncol=3, top = textGrob("No spring 2021 lockdown",just = c("centre","top"),gp=gpar(fontsize=24,fontfamily=myFont,fontface="bold"))),width=10.665,height=4.1,dpi=300,limitsize = F)
```


```{r}

Vaccinated<- vax_data %>% 
  subset(report_date>=ymd("2021-01-01") & report_date<=ymd("2021-05-29")) %>% 
  mutate(
    actual_vaccinated=total_individuals_fully_vaccinated/13924193
  )

params <- c(v=0.00268, ev=1, im=1/140, beta=0.836/4.5, l=1/5.5, rh=1/15, ro=1/14, h=0.074, dl=8.38e-05, dh=0.0147
)

initial_state_v <- c(S=12973017, E=398, I=13489,  H=934,R=268490,Fa=8726,V=659139)

times <- 0:4380


model <- ode(initial_state_v, times, SEIR, params)
summary(model)
out.df1<-as.data.frame(model)

# add a Date column and the observed incidence,fatal,hospital, and vaccinated data


 out.df1 <- out.df1 %>%
  mutate(
    Reported.Date = ymd("2021-05-30") + days(times),
    percent_vaccinated=V/13924193,
    percent_death=Fa/13924193
  )
```


```{r}
params <- c(v=0.00131, ev=1, im=1/140, beta=0.836/4.5, l=1/5.5, rh=1/15, ro=1/14, h=0.074, dl=8.38e-05, dh=0.0147
)

model <- ode(initial_state_v, times, SEIR, params)
summary(model)
out.df2<-as.data.frame(model)

# add a Date column and the observed incidence,fatal,hospital, and vaccinated data


 out.df2 <- out.df2 %>%
  mutate(
    Reported.Date = ymd("2021-05-30") + days(times),
    percent_vaccinated=V/13924193,
    percent_death=Fa/13924193
  )
```

```{r}
params <- c(v=0.000347, ev=1, im=1/140, beta=0.836/4.5, l=1/5.5, rh=1/15, ro=1/14, h=0.074, dl=8.38e-05, dh=0.0147
)

model <- ode(initial_state_v, times, SEIR, params)
summary(model)
out.df3<-as.data.frame(model)

# add a Date column and the observed incidence,fatal,hospital, and vaccinated data


 out.df3 <- out.df3 %>%
  mutate(
    Reported.Date = ymd("2021-05-30") + days(times),
    percent_vaccinated=V/13924193,
    percent_death=Fa/13924193
  )
```


```{r}

v_zoom<-ggplot(data=out.df1) +
   geom_line(aes(x=Reported.Date,y = percent_vaccinated, colour = "Vaccination rate (2021-05-29)")) +
    

  geom_line(data=out.df2,aes(x=Reported.Date,y = percent_vaccinated, colour = "Vaccination rate (Last 14 days)")) +
     #geom_line(aes(y = percent_death, colour = "Deaths")) +
  geom_line(data=out.df3,aes(x=Reported.Date,y = percent_vaccinated, colour = "Vaccination rate (Average Jan-May)")) +

  geom_point(aes(x=ymd(report_date),y=actual_vaccinated,color="Actual data"),data=Vaccinated,size=0.1)+
  
  geom_hline(yintercept=0.2,linetype="dashed") +
  geom_hline(yintercept=0.25,linetype="dashed") +
  geom_hline(yintercept=.60,linetype="dashed") +
  geom_vline(aes(xintercept = ymd("2021-05-29")),color="black",linetype="twodash") +
    
  #facet_zoom(ylim=c(0.00,0.4),xlim = c(ymd("2021-01-01"), ymd("2022-06-01")),horizontal=FALSE,zoom.size=1) +

geom_point(data = filter(out.df1, Reported.Date == "2021-08-06"),aes(x=Reported.Date,y=percent_vaccinated),color="#5A8D89")+
geom_label_repel(data = filter(out.df1, Reported.Date == "2021-08-06"),aes(x=Reported.Date,y=percent_vaccinated,label="2021-08-06",family=myFont),color="#5A8D89",
                 nudge_x = -20,nudge_y = 0.03,
                  arrow = arrow(length = unit(0.02, "npc")),
                     size= 5)+
geom_point(data = filter(out.df1, Reported.Date == "2021-09-04"),aes(x=Reported.Date,y=percent_vaccinated),color="#5A8D89")+
geom_label_repel(data = filter(out.df1, Reported.Date == "2021-09-04"),aes(x=Reported.Date,y=percent_vaccinated,label="2021-09-04",family=myFont),color="#5A8D89",
                 nudge_y = 0.06,
                  arrow = arrow(length = unit(0.02, "npc")),
                     size= 5)+
  
  geom_point(data = filter(out.df2, Reported.Date == "2021-12-29"),aes(x=Reported.Date,y=percent_vaccinated),color="#E29578")+
geom_label_repel(data = filter(out.df2, Reported.Date == "2021-12-29"),aes(x=Reported.Date,y=percent_vaccinated,label="2021-12-29",family=myFont),color="#E29578",
                 nudge_y = 0.03,
                  arrow = arrow(length = unit(0.02, "npc")),
                     size= 5)+
  geom_point(data = filter(out.df2, Reported.Date == "2022-04-17"),aes(x=Reported.Date,y=percent_vaccinated),color="#E29578")+
geom_label_repel(data = filter(out.df2, Reported.Date == "2022-04-17"),aes(x=Reported.Date,y=percent_vaccinated,label="2022-04-17",family=myFont),color="#E29578",
                 nudge_y = 0.03,
                  arrow = arrow(length = unit(0.02, "npc")),
                     size= 5)+
  annotate("text",label = "Present", x= ymd("2021-05-29"),y = 0.35,angle=90, vjust = -1,family=myFont,size=5,color="black")+
  annotate("text",label = "Step 2 reopening", x= ymd("2021-03-01"),y = 0.2,vjust = -0.5,family=myFont,size=5,color="black")+
  annotate("text",label = "Step 3 reopening", x= ymd("2021-03-01"),y = 0.25,vjust = -0.5,family=myFont,size=5,color="black")+

  scale_y_continuous(limits=c(0.00,0.4),breaks=c(0,0.1,0.2,0.25,0.3,0.4))+
  scale_x_date(limits=c(ymd("2021-01-01"), ymd("2022-06-01")),labels=date_format("%Y-%m"),breaks="4 months")+
  theme_minimal()+
  scale_colour_manual("",
    breaks=c("Actual data","Vaccination rate (2021-05-29)","Vaccination rate (Last 14 days)","Vaccination rate (Average Jan-May)"),
values=c("black","#5A8D89","#E29578","#B3AD9B"),
guide = guide_legend(override.aes = list(
                         linetype = c("blank", "solid","solid","solid"), shape=c(20,NA,NA,NA)))) +
  labs(y="Percent of the population vaccinated", x="Date") +
theme(plot.title = element_text(hjust = 0.5),text=element_text(family=myFont,size=18),
      panel.border = element_rect(colour = "#797a7c",fill=NA, size=1))
ggsave("vax_zoomed1(3).png",plot=v_zoom,width=11,height=5,dpi=300,limitsize = F)
```


```{r}
v<-ggplot(data=out.df1) +
   geom_line(aes(x=Reported.Date,y = percent_vaccinated, colour = "Vaccination rate (2021-05-29)")) +
    

  geom_line(data=out.df2,aes(x=Reported.Date,y = percent_vaccinated, colour = "Vaccination rate (Last 14 days)")) +
     #geom_line(aes(y = percent_death, colour = "Deaths")) +
  geom_line(data=out.df3,aes(x=Reported.Date,y = percent_vaccinated, colour = "Vaccination rate (Average Jan-May)")) +

  geom_point(aes(x=ymd(report_date),y=actual_vaccinated,color="Actual data"),data=Vaccinated,size=0.25)+
  
  geom_hline(yintercept=0.2,linetype="dashed") +
  geom_hline(yintercept=0.25,linetype="dashed") +
  geom_hline(yintercept=.60,linetype="dashed",color="#E31837") +
   
  geom_vline(aes(xintercept = ymd("2021-05-29")),color="black",linetype="twodash") +
    
  #facet_zoom(ylim=c(0.00,0.4),xlim = c(ymd("2021-01-01"), ymd("2022-06-01")),horizontal=FALSE,zoom.size=1) +

geom_point(data = filter(out.df1, Reported.Date == "2022-10-18"),aes(x=Reported.Date,y=percent_vaccinated),color="#5A8D89")+
geom_label_repel(data = filter(out.df1, Reported.Date == "2022-10-18"),aes(x=Reported.Date,y=percent_vaccinated,label="2022-10-18",family=myFont),color="#5A8D89",
                 nudge_x = -100,nudge_y = 0.2,
                  arrow = arrow(length = unit(0.02, "npc")),
                     size= 5)+
  
geom_point(data = filter(out.df2, Reported.Date == "2024-04-23"),aes(x=Reported.Date,y=percent_vaccinated),color="#E29578")+
geom_label_repel(data = filter(out.df2, Reported.Date == "2024-04-23"),aes(x=Reported.Date,y=percent_vaccinated,label="2024-04-23",family=myFont),color="#E29578",
                 nudge_y = -0.1,nudge_x = 200,
                  arrow = arrow(length = unit(0.02, "npc")),
                     size= 5)+
  
  geom_point(data = filter(out.df3, Reported.Date == "2032-11-02"),aes(x=Reported.Date,y=percent_vaccinated),color="#B3AD9B")+
geom_label_repel(data = filter(out.df3, Reported.Date == "2032-11-02"),aes(x=Reported.Date,y=percent_vaccinated,label="2032-11-02",family=myFont),color="#B3AD9B",
                 nudge_y = 0.1,
                  arrow = arrow(length = unit(0.02, "npc")),
                     size= 5)+
  
annotate("text",label = "Present", x= ymd("2021-05-29"),y = 0.8,angle=90, vjust = -1,family=myFont,size=5,color="black")+
annotate("text",label = "Herd immunity", x= ymd("2027-05-29"),y = 0.62,vjust=-0.1,family=myFont,size=5,color="#E31837")+
  scale_y_continuous(breaks=c(0,0.1,0.2,0.25,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1))+
  scale_x_date(labels = date_format("%Y"),breaks = "2 year") +
  theme_minimal()+
  scale_colour_manual("",
    breaks=c("Actual data","Vaccination rate (2021-05-29)","Vaccination rate (Last 14 days)","Vaccination rate (Average Jan-May)"),
values=c("black","#5A8D89","#E29578","#B3AD9B"),
guide = guide_legend(override.aes = list(
                         linetype = c("blank", "solid","solid","solid"), shape=c(20,NA,NA,NA)))) +
  labs(title="Vaccination milestones",y="Percent of the population vaccinated", x="Date") +
theme(plot.title = element_text(hjust = 0.5,face="bold"),text=element_text(family=myFont,size=18)) +
  annotate("rect", xmin=ymd("2021-01-01"), xmax=ymd("2022-06-01"), ymin=-0.03 , ymax=0.43, alpha=0.1, color="#797a7c", fill="#797a7c")
ggsave("vax(2).png",plot=v,width=11,height=5,dpi=300,limitsize = F)

  
```


```{r}
#bar plots
library(scales)
vaccine_rates <- c("0.000347\n(Average Jan-May)", "0.00131\n(Last 14 days)", "0.00268\n(2021-05-29)")
vaccine3 <- out.df1 %>%
  filter(Reported.Date <  ymd("2022-10-18"))

vaccine2 <- out.df2 %>%
  filter(Reported.Date <  ymd("2024-04-23"))

vaccine1 <- out.df3 %>%
  filter(Reported.Date <  ymd("2032-11-02"))

peak_cases <- c(max(vaccine1$I + vaccine1$E + vaccine1$H), max(vaccine2$I + vaccine2$E + vaccine2$H), max(vaccine3$I + vaccine3$E + vaccine3$H))
total_deaths <- c(max(vaccine1$Fa), max(vaccine2$Fa), max(vaccine3$Fa))

df <- data.frame(vaccine_rates, peak_cases, total_deaths)

b1<-ggplot() + 
  geom_bar(aes(x = as.factor(vaccine_rates), y = peak_cases), fill = "#e31837", stat = "identity", data = df) +
  geom_label_repel(aes(x="0.00131\n(Last 14 days)",y=2424610+200000,label="2,424,610 peak prevalent cases by this date",family=myFont),color="black",direction="y",segment.size=0.2, 
                 nudge_x=50,nudge_y = 300000,
                  arrow = arrow(length = unit(0.02, "npc")),
                     size= 4)+
  annotate("label", x = "0.000347\n(Average Jan-May)", y = 3065417+100000, label = "2032-11-02",size=4,color="#B3AD9B") +
  annotate("label", x = "0.00131\n(Last 14 days)", y = 2424610+100000, label = "2024-04-23",size=4,color="#E29578") +
  annotate("label", x = "0.00268\n(2021-05-29)", y = 1640218+100000, label = "2022-10-18",size=4,color="#5A8D89") +
  
  scale_y_continuous(limits = c(0,3500000), labels = label_comma()) +
  scale_x_discrete(labels=c("0.000347\n(Average Jan-May)", "0.00131\n(Last 14 days)", "0.00268\n(2021-05-29)"))+
  labs(title = "Peak prevalent cases before herd immunity",
       x = "Vaccination rates", y = "Peak number of prevalent cases") +
  theme_minimal() +
  theme(plot.title=element_text(hjust=2,face="bold"),panel.grid.major.x = element_blank(),text=element_text(family=myFont,size=13),
        axis.text.x=element_text(lineheight = 1))
ggsave("bar1(2).png",b1,height=5.5,width=5.35,dpi=300)


b2<-ggplot() +
  geom_bar(aes(x = as.factor(vaccine_rates), y = total_deaths), fill = "#004658", stat = "identity", data = df) +
  geom_label_repel(aes(x="0.00131\n(Last 14 days)",y=329214+75000,label="329,214 deaths by this date",family=myFont),color="black",direction="y",segment.size=0.2, 
                 nudge_x=50,nudge_y = 150000,
                  arrow = arrow(length = unit(0.02, "npc")),
                     size= 4)+
  annotate("label", x = "0.000347\n(Average Jan-May)", y = 	1184101+40000, label = "2032-11-02",size=4,color="#B3AD9B") +
  annotate("label", x = "0.00131\n(Last 14 days)", y = 	329214+40000, label = "2024-04-23",size=4,color="#E29578") +
  annotate("label", x = "0.00268\n(2021-05-29)", y = 	154438+40000, label = "2022-10-18",size=4,color="#5A8D89") +
  scale_y_continuous(breaks = c(150000, 325000, 500000, 750000, 1250000),limits=c(0,1300000), labels = label_comma()) +
  scale_x_discrete(labels=c("0.000347\n(Average Jan-May)", "0.00131\n(Last 14 days)", "0.00268\n(2021-05-29)"))+
  labs(title = "Total deaths before herd immunity",
       x = "Vaccination rates", y = "Total number of deaths") +
  theme_minimal() +
  theme(plot.title=element_text(hjust=0.5,face="bold"),panel.grid.major.x = element_blank(),text=element_text(family=myFont,size=13),
  axis.text.x=element_text(lineheight = 1))
ggsave("bar2(2).png",b2,height=5.5,width=5.35,dpi=300)
```

